### ISSUE TITLE
Does your program work only with a EEG recorders?

### ISSUE THREAD

**Issue by ordepzero** [bstadlbauer/lsl-p300-analyzer#1]
Hi,

I developed a computational model to BCI P300 Speller, but I worked with off-line data. I would like to collaborate with some  BCI P300 projects. I liked the purpose of your project.

I tried to execute start_speller.py, it worked, and start_testserver.py, it didn't wok, didn't show any message. I have all requeriments installed.

What does start_server.py really do? Is it possible to simulate the signals input, or use a file with the signals to test the program? 

Thank you!

**Comment by bstadlbauer** [comment]
Hi Pedro, 

As of now the testserver uses data recorded for the BNCI Horizon project. However, as this data was not recorded with the correct paradigm and/or the correct hardware, no averaging process can be observed with the current P300 speller, its main purpose is to test if the GUI works. 

However, it should still work (and output two LSL streams), i just tested is using a `conda` virtual env: 

```bash
conda create -n p300 python=3.6
conda activate p300 
pip install -r requirements.txt
python start_testserver.py
```

If that does not work for you, what OS are you running?

Hope that this helps, if not, feel free to ask again, 
Bernhard

**Comment by ordepzero** [comment]
Hi,

I use windows 10. With these steps I was able to run start_testserver.py.

Thank you!
